dsampler: dsampler_action.cpp dsampler.cpp dsampler_gfx.cpp dstudio_potentiometer.cpp
	g++ -o dsampler dsampler_action.cpp dsampler.cpp dsampler_gfx.cpp dstudio_potentiometer.cpp -lsfml-graphics -lsfml-window -lsfml-system

clean:
	rm -vf dsampler                       
