/*
 * Copyright 2019, 2021 Denis Salem
 *
 * This file is part of DStudio.
 *
 * DStudio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * DStudio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with DStudio. If not, see <http://www.gnu.org/licenses/>.
*/

// MISCELLANEOUS CONSTANTS
#define DSTUDIO_DOUBLE_CLICK_DELAY   0.2
#define DSTUDIO_FRAMEBUFFER_COUNT 2
#define DSTUDIO_FRAMERATE  33.3333 // Value in milliseconds 
#define DSTUDIO_ALLOCATION_REGISTER_CHUNK_SIZE 8
#define DSTUDIO_RESSOURCE_USAGE_STRING_SIZE 6
#define DSTUDIO_CHAR_SIZE_DIVISOR 16.0
#define DSTUDIO_OPEN_FILE_CHAR_PER_LINE ((int) (g_dstudio_viewport_width - 62) / 8)
#define DSTUDIO_OPEN_FILE_BASE_UI_ELEMENTS_COUNT 10
#define DSTUDIO_INSTANCE_NAME_LENGTH 27
#define DSTUDIO_PORT_NAME_LENGHT 93 // NULL Byte included
#define DSTUDIO_PROMPT_CWD_CHAR_OFFSET 11
#define DSTUDIO_NO_CALLBACK NULL
// TEXTURES SCALES

#define DSTUDIO_ADD_INSTANCE_WIDTH 68
#define DSTUDIO_ADD_INSTANCE_HEIGHT 16

#define DSTUDIO_ADD_SAMPLE_WIDTH 68
#define DSTUDIO_ADD_SAMPLE_HEIGHT 16

#define DSTUDIO_ADD_VOICE_WIDTH 68
#define DSTUDIO_ADD_VOICE_HEIGHT 16

#define DSTUDIO_CANCEL_BUTTON_COLUMNS 1
#define DSTUDIO_CANCEL_BUTTON_COUNT 1
#define DSTUDIO_CANCEL_BUTTON_OFFSET_X 252
#define DSTUDIO_CANCEL_BUTTON_OFFSET_Y 38

#define DSTUDIO_CHAR_TABLE_4X9_WIDTH 64
#define DSTUDIO_CHAR_TABLE_4X9_HEIGHT 144
#define DSTUDIO_CHAR_TABLE_8X18_WIDTH 128
#define DSTUDIO_CHAR_TABLE_8X18_HEIGHT 288

#define DSTUDIO_EXTENDED_BACKGROUND_SCALE 256

#define DSTUDIO_KNOB_1_48_WIDTH  48
#define DSTUDIO_KNOB_1_48_HEIGHT 48
#define DSTUDIO_KNOB_1_48_AREA_WIDTH  DSTUDIO_KNOB_1_48_WIDTH
#define DSTUDIO_KNOB_1_48_AREA_HEIGHT DSTUDIO_KNOB_1_48_HEIGHT

#define DSTUDIO_KNOB_1_64_WIDTH  64
#define DSTUDIO_KNOB_1_64_HEIGHT 64
#define DSTUDIO_KNOB_1_64_AREA_WIDTH  DSTUDIO_KNOB_1_64_WIDTH
#define DSTUDIO_KNOB_1_64_AREA_HEIGHT DSTUDIO_KNOB_1_64_HEIGHT

#define DSTUDIO_OPEN_FILE_ERROR_PROMPT_PADDING_RIGHT 160
#define DSTUDIO_OPEN_FILE_BUTTON_COLUMNS 1
#define DSTUDIO_OPEN_FILE_BUTTON_COUNT 1
#define DSTUDIO_OPEN_FILE_BUTTON_OFFSET_X 92
#define DSTUDIO_OPEN_FILE_BUTTON_OFFSET_Y 18
#define DSTUDIO_OPEN_FILE_BUTTONS_WIDTH 68
#define DSTUDIO_OPEN_FILE_BUTTONS_HEIGHT 16

#define DSTUDIO_OPEN_FILE_LIST_BOX_HEIGHT (g_dstudio_viewport_height - 76)
#define DSTUDIO_OPEN_FILE_LIST_OFFSET_X 32

#define DSTUDIO_OPEN_FILE_LIST_HIGHLIGHT_POS_X \
    (-1.0 + ((GLfloat) DSTUDIO_OPEN_FILE_CHAR_PER_LINE*8) / g_dstudio_viewport_width) + ((GLfloat) ((DSTUDIO_OPEN_FILE_LIST_OFFSET_X >> 1) + 8)/ g_dstudio_viewport_width)

#define DSTUDIO_OPEN_FILE_LIST_HIGHLIGHT_OFFSET_Y (-18.0 / (GLfloat) (g_dstudio_viewport_height >> 1))

#define DSTUDIO_OPEN_FILE_PROMPT_AREA_WIDTH 72
#define DSTUDIO_OPEN_FILE_PROMPT_AREA_HEIGHT 18
#define DSTUDIO_OPEN_FILE_PROMPT_BUFFER_SIZE 9
#define DSTUDIO_OPEN_FILE_PROMPT_COLUMN 1
#define DSTUDIO_OPEN_FILE_PROMPT_COUNT 1
#define DSTUDIO_OPEN_FILE_PROMPT_OFFSET_X 32
#define DSTUDIO_OPEN_FILE_PROMPT_OFFSET_Y 38
#define DSTUDIO_OPEN_FILE_PROMPT_PADDING 24

#define DSTUDIO_OPEN_FILE_SLIDER_WIDTH 18
#define DSTUDIO_OPEN_FILE_SLIDER_HEIGHT 18

#define DSTUDIO_OPEN_FILE_SLIDER_BACKGROUND_OFFSET_X 42

#define DSTUDIO_OPEN_FILE_PROMPT_BOX_OFFSET_Y 38
#define DSTUDIO_OPEN_FILE_PROMPT_BOX_AREA_HEIGHT 26

#define DSTUDIO_PATTERN_SCALE 16

#define DSTUDIO_RESSOURCE_USAGE_WIDTH 30
#define DSTUDIO_RESSOURCE_USAGE_HEIGHT 24

#define DSTUDIO_SLIDER_1_10_WIDTH 10
#define DSTUDIO_SLIDER_1_10_HEIGHT 10
#define DSTUDIO_SLIDER_1_10_AREA_WIDTH DSTUDIO_SLIDER_1_10_WIDTH
#define DSTUDIO_SLIDER_1_10_AREA_HEIGHT 42

#define DSTUDIO_SLIDER_2_8_WIDTH 8
#define DSTUDIO_SLIDER_2_8_HEIGHT 8
#define DSTUDIO_SLIDER_2_8_AREA_WIDTH DSTUDIO_SLIDER_2_8_WIDTH
#define DSTUDIO_SLIDER_2_8_AREA_HEIGHT 95

#define DSTUDIO_SLIDER_BACKGROUND_WIDTH 18
#define DSTUDIO_SLIDER_BACKGROUND_HEIGHT 27

#define DSTUDIO_TEXT_POINTER_WIDTH 1
#define DSTUDIO_TEXT_POINTER_1_HEIGHT DSTUDIO_CHAR_TABLE_4X9_HEIGHT / 13
#define DSTUDIO_TEXT_POINTER_2_HEIGHT DSTUDIO_CHAR_TABLE_8X18_HEIGHT / 13

#define DSANDGRAINS_TINY_BUTTON_SCALE 32

// UI ELEMENTS FLAGS
#define DSTUDIO_FLAG_NONE                           0
#define DSTUDIO_FLAG_FLIP_Y                         1
#define DSTUDIO_FLAG_USE_ALPHA                      2
#define DSTUDIO_FLAG_USE_ANTI_ALIASING              4
#define DSTUDIO_FLAG_USE_TEXT_SETTING               8
#define DSTUDIO_FLAG_TEXTURE_IS_PATTERN             16
#define DSTUDIO_FLAG_IS_VISIBLE                     32
#define DSTUDIO_FLAG_USE_SLIDER_BACKGROUND_SETTING  64
#define DSTUDIO_FLAG_SLIDER_TO_TOP                  128
#define DSTUDIO_FLAG_RESET_HIGHLIGHT_AREAS          256
#define DSTUDIO_FLAG_OVERLAP                        512
#define DSTUDIO_FLAG_ANIMATE_MOTION                      1024
#define DSTUDIO_FLAG_ANIMATE_OFFSET                      2048
#define DSTUDIO_FLAG_ANIMATE_ALPHA                       4096
#define DSTUDIO_FLAG_ANIMATE \
            (DSTUDIO_FLAG_ANIMATE_MOTION | \
            DSTUDIO_FLAG_ANIMATE_OFFSET | \
            DSTUDIO_FLAG_ANIMATE_ALPHA)
            
#define DSTUDIO_FAILURE_IS_FATAL 1
#define DSTUDIO_FAILURE_IS_NOT_FATAL 0

#define DSTUDIO_DO_ANIMATE 1
#define DSTUDIO_DO_NOT_ANIMATE 0

#define DSTUDIO_OPEN_FILE_MENU_CONSUME_CANCEL_CALLBACK   1
#define DSTUDIO_OPEN_FILE_MENU_CONSUME_NO_CALLBACK       0 
